apiVersion: v1
kind: Service
metadata:
  name: dev-mshopping-service
  namespace: dev-mshopping
  labels:
    env: dev-mshopping
    app: mshopping
    layer: frontend
spec:
  type: ClusterIP
  selector:
    app: mshopping
  ports:
    - name: http
      port: 8080
      targetPort: 8080