apiVersion: v1
kind: ConfigMap
metadata:
  name: preprod-mshopping-deployment-application-config
  namespace: preprod-mshopping
  labels:
    env: preprod-mshopping
    app: mshopping
    layer: frontend
data:
  application.properties: |-
    DB_URL=jdbc:mysql://dummy-db.dev.local:3306/mshopping
    DB_USERNAME=dev_user
    DB_PASSWORD=dev_password124

    KAFKA_URL=dummy-kafka.dev.local:9092